name: Build Custom Sandboxie

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Rename references
      run: |
        (Get-Content -Path .\Sandboxie\core\dl\pnp.c) -replace 'SbieDrv', 'MyCustomDrv' | Set-Content -Path .\Sandboxie\core\dl\pnp.c
        (Get-Content -Path .\Sandboxie\core\svc\Version.h) -replace 'SbieDll', 'MyCustomDll' | Set-Content -Path .\Sandboxie\core\svc\Version.h

    - name: Build Sandboxie
      run: msbuild /p:Configuration=Release /p:Platform=x64 Sandboxie.sln

    - name: Download latest official release
      run: |
        $url = "https://github.com/sandboxie-plus/Sandboxie/releases/latest/download/Sandboxie-Classic-x64-v5.55.6.exe"
        Invoke-WebRequest -Uri $url -OutFile Sandboxie-Latest.exe

    - name: Extract signed driver
      run: |
        & .\Sandboxie-Latest.exe /S /ExtractCab
        $driverPath = Get-ChildItem -Path .\Sandboxie-Classic | Where-Object { $_.Name -like "SbieDrv.sys" } | Select-Object -ExpandProperty FullName
        Move-Item -Path $driverPath -Destination .\Sandboxie\core\drv\SbieDrv.sys

    - name: Zip the output
      run: |
        Compress-Archive -Path .\Sandboxie\* -DestinationPath CustomSandboxie.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: custom-sandboxie
        path: CustomSandboxie.zip
